//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Pegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_BUSINESS
    {
        public int ID { get; set; }
        public Nullable<int> BUSINESS_AGE { get; set; }
        public string PROVINCE { get; set; }
        public string REGENCY { get; set; }
        public string SUB_DISTRICT { get; set; }
        public string ADDRESS { get; set; }
        public string PICTURE { get; set; }
        public int BUSINESS_FINANCING_ID { get; set; }
    
        public virtual TYPE_BUSINESS_FINANCING TYPE_BUSINESS_FINANCING { get; set; }
    }
}
