//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Pegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_TYPE_VEHICLE
    {
        public int ID { get; set; }
        public string POLICE_NUMBER { get; set; }
        public string STNK_NUMBER { get; set; }
        public string MACHINE_NUMBER { get; set; }
        public string BPKB_NUMBER { get; set; }
        public string BPKB_OWNER { get; set; }
        public string PICTURE { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
        public int TYPE_VEHICLE_ID { get; set; }
    
        public virtual TYPE_VEHICLE TYPE_VEHICLE { get; set; }
    }
}
