//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Pegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANDPHONE
    {
        public int ID { get; set; }
        public string BRAND { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> YEARS_OF_BUY { get; set; }
        public Nullable<decimal> SELLING_PRICE { get; set; }
        public string CONDITION { get; set; }
        public string PICTURE { get; set; }
        public int TRANSACTION_ID { get; set; }
    
        public virtual TRANSACTION TRANSACTION { get; set; }
    }
}
