//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Pegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOLD_SAVING
    {
        public int ID { get; set; }
        public Nullable<long> ACCOUNT_NUMBER { get; set; }
        public Nullable<int> BALANCE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public int TRANSACTION_ID { get; set; }
    
        public virtual TRANSACTION TRANSACTION { get; set; }
    }
}
