//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Pegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOLD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOLD()
        {
            this.JEWELRies = new HashSet<JEWELRY>();
        }
    
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string UNIT { get; set; }
        public decimal SELLING_PRICE { get; set; }
        public decimal PURCHASE_PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JEWELRY> JEWELRies { get; set; }
    }
}
