//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Pegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACTION()
        {
            this.ELECTRONICs = new HashSet<ELECTRONIC>();
            this.GOLD_SAVING = new HashSet<GOLD_SAVING>();
            this.HANDPHONEs = new HashSet<HANDPHONE>();
            this.INSTALLMENTs = new HashSet<INSTALLMENT>();
            this.JEWELRies = new HashSet<JEWELRY>();
            this.PRECIOUS_METAL = new HashSet<PRECIOUS_METAL>();
            this.TYPE_BUSINESS_FINANCING = new HashSet<TYPE_BUSINESS_FINANCING>();
            this.TYPE_LAPTOP = new HashSet<TYPE_LAPTOP>();
            this.TYPE_VEHICLE = new HashSet<TYPE_VEHICLE>();
        }
    
        public int ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public int INSTALLMENT_TYPE_ID { get; set; }
        public int OUTLET_ID { get; set; }
        public byte[] TRANSACTIONS_DATE { get; set; }
        public decimal ADMINISTRATIVE_COST { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public Nullable<System.DateTime> approved_status { get; set; }
        public Nullable<System.DateTime> accepted_date { get; set; }
        public string accepted_status { get; set; }
        public Nullable<decimal> remaining_amount { get; set; }
        public Nullable<decimal> loan_amount { get; set; }
        public int user_id { get; set; }
        public string transaction_no { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ELECTRONIC> ELECTRONICs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOLD_SAVING> GOLD_SAVING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HANDPHONE> HANDPHONEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTALLMENT> INSTALLMENTs { get; set; }
        public virtual INSTALLMENT_TYPE INSTALLMENT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JEWELRY> JEWELRies { get; set; }
        public virtual OUTLET OUTLET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRECIOUS_METAL> PRECIOUS_METAL { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TYPE_BUSINESS_FINANCING> TYPE_BUSINESS_FINANCING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TYPE_LAPTOP> TYPE_LAPTOP { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TYPE_VEHICLE> TYPE_VEHICLE { get; set; }
    }
}
