//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Pegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_VEHICLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TYPE_VEHICLE()
        {
            this.DETAIL_TYPE_VEHICLE = new HashSet<DETAIL_TYPE_VEHICLE>();
        }
    
        public int ID { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public string BRAND { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> CYLINDER { get; set; }
        public Nullable<int> YEARS_OF_BUY { get; set; }
        public Nullable<decimal> MARKET_PRICE { get; set; }
        public string DESCRIPTION { get; set; }
        public int TRANSACTION_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_TYPE_VEHICLE> DETAIL_TYPE_VEHICLE { get; set; }
        public virtual TRANSACTION TRANSACTION { get; set; }
    }
}
