//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Pegadaian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_BUSINESS_FINANCING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TYPE_BUSINESS_FINANCING()
        {
            this.DETAIL_BUSINESS = new HashSet<DETAIL_BUSINESS>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> CAPITAL_REQUIREMENT { get; set; }
        public string BUSINESS_TYPE { get; set; }
        public Nullable<decimal> TURNOVER { get; set; }
        public Nullable<decimal> PROFIT { get; set; }
        public int TRANSACTION_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_BUSINESS> DETAIL_BUSINESS { get; set; }
        public virtual TRANSACTION TRANSACTION { get; set; }
    }
}
